"""Initial migration

Revision ID: 1537eb8fb589
Revises: 
Create Date: 2025-06-22 18:57:12.204656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1537eb8fb589'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grows', schema=None) as batch_op:
        batch_op.add_column(sa.Column('syringe_status', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('spawn_status', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('bulk_status', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('fruiting_status', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grows', schema=None) as batch_op:
        batch_op.drop_column('fruiting_status')
        batch_op.drop_column('bulk_status')
        batch_op.drop_column('spawn_status')
        batch_op.drop_column('syringe_status')

    # ### end Alembic commands ###
