"""Add space field to grow

Revision ID: 5bbf3a91fa29
Revises: 1537eb8fb589
Create Date: 2025-06-22 18:13:00.848974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bbf3a91fa29'
down_revision: Union[str, Sequence[str], None] = '1537eb8fb589'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grows', schema=None) as batch_op:
        batch_op.add_column(sa.Column('space', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grows', schema=None) as batch_op:
        batch_op.drop_column('space')

    # ### end Alembic commands ###
