"""Add optimal conditions fields to grow

Revision ID: b08e2011bad5
Revises: 2477ddef952c
Create Date: 2025-06-27 10:58:51.266810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b08e2011bad5'
down_revision: Union[str, Sequence[str], None] = '2477ddef952c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grows', schema=None) as batch_op:
        batch_op.add_column(sa.Column('optimal_spawn_temp_low', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('optimal_spawn_temp_high', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('optimal_bulk_temp_low', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('optimal_bulk_temp_high', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('optimal_bulk_humidity_low', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('optimal_bulk_humidity_high', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('optimal_bulk_co2_low', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('optimal_bulk_co2_high', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('optimal_fruiting_temp_low', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('optimal_fruiting_temp_high', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('optimal_fruiting_humidity_low', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('optimal_fruiting_humidity_high', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('optimal_fruiting_co2_low', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('optimal_fruiting_co2_high', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('optimal_fruiting_light_low', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('optimal_fruiting_light_high', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('conditions_inputs_hash', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grows', schema=None) as batch_op:
        batch_op.drop_column('conditions_inputs_hash')
        batch_op.drop_column('optimal_fruiting_light_high')
        batch_op.drop_column('optimal_fruiting_light_low')
        batch_op.drop_column('optimal_fruiting_co2_high')
        batch_op.drop_column('optimal_fruiting_co2_low')
        batch_op.drop_column('optimal_fruiting_humidity_high')
        batch_op.drop_column('optimal_fruiting_humidity_low')
        batch_op.drop_column('optimal_fruiting_temp_high')
        batch_op.drop_column('optimal_fruiting_temp_low')
        batch_op.drop_column('optimal_bulk_co2_high')
        batch_op.drop_column('optimal_bulk_co2_low')
        batch_op.drop_column('optimal_bulk_humidity_high')
        batch_op.drop_column('optimal_bulk_humidity_low')
        batch_op.drop_column('optimal_bulk_temp_high')
        batch_op.drop_column('optimal_bulk_temp_low')
        batch_op.drop_column('optimal_spawn_temp_high')
        batch_op.drop_column('optimal_spawn_temp_low')

    # ### end Alembic commands ###
