"""Add relative humidity fields

Revision ID: d2344e848cb3
Revises: b08e2011bad5
Create Date: 2025-06-27 16:39:59.998772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2344e848cb3'
down_revision: Union[str, Sequence[str], None] = 'b08e2011bad5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grows', schema=None) as batch_op:
        batch_op.add_column(sa.Column('optimal_bulk_relative_humidity_low', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('optimal_bulk_relative_humidity_high', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('optimal_fruiting_relative_humidity_low', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('optimal_fruiting_relative_humidity_high', sa.Float(), nullable=True))
        batch_op.drop_column('optimal_bulk_humidity_high')
        batch_op.drop_column('optimal_fruiting_humidity_high')
        batch_op.drop_column('optimal_bulk_humidity_low')
        batch_op.drop_column('optimal_fruiting_humidity_low')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grows', schema=None) as batch_op:
        batch_op.add_column(sa.Column('optimal_fruiting_humidity_low', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('optimal_bulk_humidity_low', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('optimal_fruiting_humidity_high', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('optimal_bulk_humidity_high', sa.FLOAT(), nullable=True))
        batch_op.drop_column('optimal_fruiting_relative_humidity_high')
        batch_op.drop_column('optimal_fruiting_relative_humidity_low')
        batch_op.drop_column('optimal_bulk_relative_humidity_high')
        batch_op.drop_column('optimal_bulk_relative_humidity_low')

    # ### end Alembic commands ###
